apiVersion: v1
kind: Deployment
metadata:
  name: alpaca-prod
  labels: 
    ver: '1'
    app: alpaca
    env: prod
spec:
  replicas: 3
  containers:
    - image: dougoleary/kuard-amd64:blue
      name: alpaca-prod
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
