---
- name: set permissive
  selinux:
    policy: targeted
    state: permissive

- name: ensure selinux stays that way
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'

- name: remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent

- name: disable swap
  command: /usr/sbin/swapoff -a

- name: br_netfilter to get loaded on boot
  copy:
    src: files/br_netfiler.conf
    dest: /etc/modules-load.d/br_netfiler.conf
    owner: root
    group: root
    mode: '0644'

- name: load br_netfilter module
  command: /usr/sbin/modprobe br_netfilter

- name: set ipv4 bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: set ipv6 bridge
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present

- name: Send repo files
  copy:
    src: files/{{item}}
    dest: /etc/yum.repos.d/{{item}}
    owner: root
    group: root
    mode: '0644'
  loop:
    - docker-ce.repo
    - kubernetes.repo

- name: Install kubernetes and docker
  yum:
    name: 
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - kubeadm 
      - kubectl
      - kubelet
    enablerepo: 
      - docker-ce-stable
      - kubernetes
      - rhel-7-server-rhui-extras-rpms
    state: present

- name: enable services
  service:
    name: "{{item}}"
    state: started
    enabled: true
  loop:
    - docker
    - kubelet
      
